version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_ci
    image: ${IMAGE_NAME_WITH_TAG}
    restart: unless-stopped
    working_dir: /var/www/html
    networks:
      - laravel-network
    depends_on:
      - db

  webserver:
    build:
      context: ./docker-compose/nginx
      dockerfile: Dockerfile
    container_name: laravel_nginx_ci
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - laravel-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db_ci
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db-data:
    driver: local
